### ISSUE TITLE
Question: why this iso so big?

### ISSUE THREAD

**Issue by lvxingtu** [EmreTech/T2-Gentoo-Kernel#3]
arch, only 787 MB
this need 1.45g

**Comment by lvxingtu** [comment]
I find other system also big, sorry for this stupid question

**Comment by EmmmaTech** [comment]
What? This repo doesn't produce an ISO. This repo only produces a kernel.

**Comment by EmmmaTech** [comment]
I was working on a repo that would produce an ISO but like this repo I put it on hold until I have more time to work on it.

That ISO repo isn't even public yet nor is it in this organization.

**Comment by EmmmaTech** [comment]
Closing as invalid.
